name: build-publish

env:
  DOCKER_IMAGE_NAME: paniclobster/devcontainer-base

on:
  push:
    tags:
      - v*.*.*

jobs:
  build-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - variant: alpine
            tagLatest: alpine
            tagSuffix: alpine
          - variant: debian
            tagLatest: latest
            tagSuffix: ""
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2.3.4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.5.1
      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Get release version
        id: get_release_version
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/v}
      - name: Build and Push the Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./${{ matrix.variant }}
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ steps.get_release_version.outputs.tag }}${{ matrix.tagSuffix }},${{ env.DOCKER_IMAGE_NAME }}:${{ matrix.tagLatest }}
