name: dive-analysis

env:
  DOCKER_IMAGE_NAME: paniclobster/devcontainer-base

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dive-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
          - alpine
          - debian
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2.3.4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.4.1
      - name: Build the Docker image
        uses: docker/build-push-action@v2.6.1
        with:
          context: ./${{ matrix.variant }}
          load: true
          push: false
          tags: ${{ env.DOCKER_IMAGE_NAME }}:latest
      - name: Install dive
        run: |
          curl --silent https://api.github.com/repos/wagoodman/dive/releases | grep browser_download | grep linux | cut -d '"' -f 4 | grep -e /dive_.*\.deb | sort | tail -n 1 | xargs curl --location --output dive.deb --silent
          sudo apt install ./dive.deb
      - name: Perform dive analysis
        run: dive ${{ env.DOCKER_IMAGE_NAME }}:latest
