name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  alpine-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3.0.2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Login to GitHub container registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./alpine
          push: true
          tags: "ghcr.io/paniclobster/devcontainer-base:test-alpine"
      - name: Test setup scripts
        uses: docker/build-push-action@v2.10.0
        with:
          build-args: |
            BASE_IMAGE=ghcr.io/paniclobster/devcontainer-base:test-alpine
          context: ./tests/alpine
          push: false
  debian-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3.0.2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Login to GitHub container registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./debian
          push: true
          tags: "ghcr.io/paniclobster/devcontainer-base:test"
      - name: Test setup scripts
        uses: docker/build-push-action@v2.10.0
        with:
          build-args: |
            BASE_IMAGE=ghcr.io/paniclobster/devcontainer-base:test
          context: ./tests/debian
          push: false
