name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  alpine-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3.3.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Load the Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./alpine
          push: true
          tags: ghcr.io/paniclobster/devcontainer-base:test-alpine
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Test setup scripts
        uses: docker/build-push-action@v4.0.0
        with:
          build-args: |
            BASE_IMAGE=ghcr.io/paniclobster/devcontainer-base:test-alpine
          context: ./tests/alpine
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
  debian-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3.3.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Load the Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./debian
          push: true
          tags: ghcr.io/paniclobster/devcontainer-base:test-debian
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Test setup scripts
        uses: docker/build-push-action@v4.0.0
        with:
          build-args: |
            BASE_IMAGE=ghcr.io/paniclobster/devcontainer-base:test-debian
          context: ./tests/debian
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
